### ISSUE TITLE
Conflict with Better Enchanted Books enchantment sorting

### ISSUE THREAD

**Issue by Fourmisain** [Devan-Kerman/Trident-Return#1]
This took quite a while to debug!

I was wondering why this mod wouldn't work on a server with a [bigger mod pack](https://github.com/FettLol/fettlol-modpack), but would work in singleplayer.
It did say it's a clientside mod, so I was confused at first. I then tested it on my server as well and there it worked just fine!

Long story short: 

https://github.com/Devan-Kerman/Trident-Return/blob/1bdb88f1e70bed2416f47ea14ac13f494b793382/src/main/java/net/devtech/trident_return/TridentReturn.java#L45

can fail when Better Enchanted Books is installed because it sorts/reorders the client-side enchantments `ListTag`, e.g. like so:

> acd.get("Enchantments") = [{lvl:1s,id:"minecraft:mending"},{lvl:3s,id:"minecraft:loyalty"},{lvl:5s,id:"minecraft:impaling"},{lvl:3s,id:"minecraft:unbreaking"}]
> abd.get("Enchantments") = [{lvl:5s,id:"minecraft:impaling"},{lvl:3s,id:"minecraft:loyalty"},{lvl:1s,id:"minecraft:mending"},{lvl:3s,id:"minecraft:unbreaking"}]

and thus the `CompountTag.equals()` fails.

---

Better Enchanted Books sorting can be turned "off", but since I worked on the code I know [it can still put curses at the bottom](https://github.com/Bernasss12/BetterEnchantedBooks/blob/266a9a920690ae46be8c08c1587fae9f33b34441/src/main/java/dev/bernasss12/bebooks/util/NBTUtils.java#L39-L41), I believe that can be turned off as well, so there is at least a workaround for the issue.

One compatibility fix on this side would be to sort (a copy of) both `acd.get("Enchantments")` and `abd.get("Enchantments")` and then test for their equality separately, just like the "Damage" tag is checked separately.

Ideally, this should be fixed in Better Enchanted Books, but I'm not confident this will happen - maybe I'll (eventually) look into it, there might be an easy fix.

**Comment by Devan-Kerman** [comment]
I can fix this, but in my opinion, BEB should fix it, this is a common check so it will break a lot of other mods as well, I can submit a PR to BEB in a bit

**Comment by Devan-Kerman** [comment]
https://github.com/Bernasss12/BetterEnchantedBooks/pull/36
